/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Phan Huu Tuong
 */
public class FormChinh extends javax.swing.JFrame {
    // Khai báo biến toàn cục để lưu thông tin người đang đăng nhập
    public static String maNVDangNhap = ""; 
    public static String tenNVDangNhap = ""; 

    // --- HÀM KHỞI TẠO NHẬN 3 THAM SỐ (Phải khớp với bên Đăng Nhập) ---
    public FormChinh(String quyen, String maNV, String hoTen) {
      initComponents();
        this.setLocationRelativeTo(null);
        
        maNVDangNhap = maNV;
        
        // --- SỬA LẠI ĐOẠN NÀY ---
        // Logic mới: Kiểm tra nếu chức vụ LÀ "Admin" hoặc "Quản lý" thì mở, còn lại khóa hết.
        if (quyen.equalsIgnoreCase("Admin") || quyen.equalsIgnoreCase("Quản lý")) {
            this.setTitle("Hệ thống Quản Lý - ADMIN");
            btnNhanVien.setEnabled(true); // Mở nút
        } else {
            // Các trường hợp còn lại (Kế toán, Nhân viên, Bán hàng...) -> KHÓA NÚT
            this.setTitle("Hệ thống - Nhân Viên: " + hoTen);
            btnNhanVien.setEnabled(false); // Khóa nút (Làm mờ)
            
            // Nếu muốn ẩn luôn thì dùng: btnNhanVien.setVisible(false);
        }
    }
    
    // Hàm mặc định (giữ lại để test)
    public FormChinh() {
        initComponents();
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormChinh.class.getName());

    /**
     * Creates new form FormChinh
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNhanVien = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("HỆ THỐNG QUẢN LÝ CỬA HÀNG LAPTOP");

        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnNhanVien.setText("Quản lý Nhân Viên");
        btnNhanVien.addActionListener(this::btnNhanVienActionPerformed);

        btnKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnKhachHang.setText("Quản lý Khách Hàng");
        btnKhachHang.addActionListener(this::btnKhachHangActionPerformed);

        btnHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHoaDon.setText("Quản lý Hóa Đơn");
        btnHoaDon.addActionListener(this::btnHoaDonActionPerformed);

        btnSanPham.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSanPham.setText("Quản lý Sản Phẩm ");
        btnSanPham.addActionListener(this::btnSanPhamActionPerformed);

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(this::btnDangXuatActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKhachHang)
                            .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDangXuat)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhanVien)
                    .addComponent(btnKhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoaDon)
                    .addComponent(btnSanPham))
                .addGap(34, 34, 34)
                .addComponent(btnDangXuat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
         FormNhanVien frm = new FormNhanVien();
        frm.setVisible(true);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        FormKhachHang frm = new FormKhachHang();
        frm.setVisible(true);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        new DangNhap().setVisible(true); // Mở lại form đăng nhập
        this.dispose(); // Đóng form chính này đi
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        FormHoaDon frm = new FormHoaDon();
        frm.setVisible(true);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        FormSanPham frm = new FormSanPham();
        frm.setVisible(true);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormChinh().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
