/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Phan Huu Tuong
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormNhanVien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormNhanVien.class.getName());

    /**
     * Creates new form FormNhanVien
     */
    public FormNhanVien() {
        initComponents();
        this.setLocationRelativeTo(null); // 1. Đưa form ra giữa màn hình
        // 2. Chỉnh chế độ đóng form: Chỉ tắt form này, không tắt cả chương trình
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       // Gọi hàm tải dữ liệu
        loadData(); 
        
        // --- DÁN CODE CHỈNH FONT Ở ĐÂY (NGAY DƯỚI loadData) ---
        
        // 1. Chỉnh font Tiêu Đề (Header) to và đậm
        tblNhanVien.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        
        // 2. Chỉnh font Nội Dung (Rows) to vừa phải
        tblNhanVien.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        
        // 3. Tăng chiều cao dòng lên 30px cho thoáng
        tblNhanVien.setRowHeight(30);
    }
    // --- HÀM TẢI DỮ LIỆU TỪ MYSQL LÊN BẢNG ---
    private void loadData() {
        try {
            Connection conn = DBConnect.getConnection();
            
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL!");
                return;
            }

            // 1. Câu lệnh SQL lấy toàn bộ nhân viên
            String sql = "SELECT * FROM NhanVien";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            // 2. Tạo mô hình bảng (Cấu trúc cột)
            DefaultTableModel model = new DefaultTableModel();
            // Định nghĩa các cột giống hệt trong Database
            model.addColumn("Mã NV"); 
            model.addColumn("Họ Tên");
            model.addColumn("Chức Vụ");
            model.addColumn("Ngày Sinh");
            model.addColumn("Lương");
            model.addColumn("Tài Khoản");
            model.addColumn("Mật Khẩu");
            
            // 3. Duyệt qua từng dòng dữ liệu lấy được và thêm vào model
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getInt("MaNV"));
                row.add(rs.getString("HoTen"));
                row.add(rs.getString("ChucVu"));
                row.add(rs.getDate("NgaySinh"));
                row.add((long) rs.getDouble("Luong"));
                row.add(rs.getString("TaiKhoan"));
                row.add(rs.getString("MatKhau"));
                
                model.addRow(row); // Thêm dòng vào model
            }
            
            // 4. Gán model vừa tạo vào bảng tblNhanVien
            tblNhanVien.setModel(model);
            
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Họ tên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Chức vụ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Ngày sinh:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Lương:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Tài khoản:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Mật khẩu:");

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtHoTen.addActionListener(this::txtHoTenActionPerformed);

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtNgaySinh.addActionListener(this::txtNgaySinhActionPerformed);

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtLuong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTaiKhoan.addActionListener(this::txtTaiKhoanActionPerformed);

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtMatKhau.addActionListener(this::txtMatKhauActionPerformed);

        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên", "Chức vụ", "Ngày sinh", "Lương", "Tài khoản", "Mật khẩu"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Mã NV:");

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtMaNV.addActionListener(this::txtMaNVActionPerformed);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnHome.addActionListener(this::btnHomeActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setText("Tìm Nhân Viên theo Mã NV/Họ tên:");

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(btnThem)
                                .addGap(69, 69, 69)
                                .addComponent(btnSua)
                                .addGap(63, 63, 63)
                                .addComponent(btnXoa)
                                .addGap(62, 62, 62)
                                .addComponent(btnLamMoi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txtHoTen)
                                    .addComponent(txtChucVu)
                                    .addComponent(txtNgaySinh)
                                    .addComponent(txtLuong))
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTaiKhoan)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLamMoi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa)
                        .addComponent(btnSua)
                        .addComponent(btnThem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
      // 1. Lấy dữ liệu từ giao diện
    String maNV = txtMaNV.getText(); // <--- MỚI
    String hoten = txtHoTen.getText();
    String chucvu = txtChucVu.getText();
    String ngaysinh = txtNgaySinh.getText(); 
    String luong = txtLuong.getText();
    String taikhoan = txtTaiKhoan.getText();
    String matkhau = txtMatKhau.getText();

    // 2. Kiểm tra nhập thiếu (Phải kiểm tra cả Mã NV)
    if(maNV.equals("") || hoten.equals("")){
        JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã NV và Họ tên!");
        return;
    }

    try {
        Connection conn = DBConnect.getConnection();
        
        // --- CÂU SQL MỚI: Có thêm cột MaNV ở đầu ---
        String sql = "INSERT INTO NhanVien (MaNV, HoTen, ChucVu, NgaySinh, Luong, TaiKhoan, MatKhau) VALUES (?,?,?,?,?,?,?)";
        
        PreparedStatement ps = conn.prepareStatement(sql);
        
        ps.setInt(1, Integer.parseInt(maNV)); // <--- Set tham số số 1 là Mã NV
        ps.setString(2, hoten);
        ps.setString(3, chucvu);
        ps.setString(4, ngaysinh);
        ps.setDouble(5, Double.parseDouble(luong));
        ps.setString(6, taikhoan);
        ps.setString(7, matkhau);
        
        ps.executeUpdate(); 
        
        JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
        loadData(); 
        conn.close();
    } catch (Exception e) {
        // Bắt lỗi trùng Mã NV (Ví dụ nhập số 1 hai lần)
        if(e.getMessage().contains("Duplicate entry")){
            JOptionPane.showMessageDialog(this, "Mã nhân viên " + maNV + " đã tồn tại! Vui lòng chọn số khác.");
        } else {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi thêm: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblNhanVien.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên để sửa!");
        return;
    }
    
    try {
        // Lấy Mã NV để biết đang sửa ai (Mã NV không được sửa)
        String maNV = tblNhanVien.getValueAt(row, 0).toString();
        
        Connection conn = DBConnect.getConnection();
        String sql = "UPDATE NhanVien SET HoTen=?, ChucVu=?, NgaySinh=?, Luong=?, TaiKhoan=?, MatKhau=? WHERE MaNV=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        
        ps.setString(1, txtHoTen.getText());
        ps.setString(2, txtChucVu.getText());
        ps.setString(3, txtNgaySinh.getText());
        ps.setDouble(4, Double.parseDouble(txtLuong.getText()));
        ps.setString(5, txtTaiKhoan.getText());
        ps.setString(6, txtMatKhau.getText());
        ps.setString(7, maNV); // Điều kiện WHERE
        
        ps.executeUpdate();
        
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        loadData();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi sửa: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // 1. Kiểm tra xem người dùng đã chọn dòng nào chưa
    int row = tblNhanVien.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa trên bảng!");
        return;
    }

    // 2. Hỏi xác nhận cho chắc ăn
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa nhân viên này?");
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Lấy MaNV ở cột đầu tiên (cột 0) của dòng đang chọn
            String maNV = tblNhanVien.getValueAt(row, 0).toString();
            
            Connection conn = DBConnect.getConnection();
            String sql = "DELETE FROM NhanVien WHERE MaNV = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, maNV);
            
            ps.executeUpdate(); // Thực thi xóa
            
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            loadData(); // Tải lại bảng
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi xóa: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
       // 1. Xóa trắng ô Mã NV (Thêm dòng này vào)
    txtMaNV.setText(""); 
    
    // 2. Các ô cũ giữ nguyên
    txtHoTen.setText("");
    txtChucVu.setText("");
    txtNgaySinh.setText("");
    txtLuong.setText("");
    txtTaiKhoan.setText("");
    txtMatKhau.setText("");
    
    // 3. Đặt con trỏ chuột về ô Mã NV để nhập luôn cho tiện
    txtMaNV.requestFocus();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
       // Lấy dòng đang được chọn
    int row = tblNhanVien.getSelectedRow();
    
    if (row >= 0) {
        // --- DÒNG QUAN TRỌNG BẠN ĐANG THIẾU ---
        // Lấy dữ liệu cột 0 (Mã NV) đổ vào ô txtMaNV
        txtMaNV.setText(tblNhanVien.getValueAt(row, 0).toString()); 
        
        // Các cột còn lại
        txtHoTen.setText(tblNhanVien.getValueAt(row, 1).toString());
        txtChucVu.setText(tblNhanVien.getValueAt(row, 2).toString());
        txtNgaySinh.setText(tblNhanVien.getValueAt(row, 3).toString());
        
        // Xử lý hiển thị lương (chuyển về số nguyên cho đẹp nếu cần)
        txtLuong.setText(tblNhanVien.getValueAt(row, 4).toString());
        
        txtTaiKhoan.setText(tblNhanVien.getValueAt(row, 5).toString());
        txtMatKhau.setText(tblNhanVien.getValueAt(row, 6).toString());
    }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
       // 1. Mở lại Form Chính
    new FormChinh().setVisible(true);
    
    // 2. Đóng Form Nhân Viên hiện tại đi
    this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        // 1. Lấy từ khóa người dùng nhập và cắt khoảng trắng thừa
    String tuKhoa = txtTimKiem.getText().trim();
    
    // Nếu ô trống -> Tải lại toàn bộ danh sách (Co như nút Làm mới)
    if (tuKhoa.isEmpty()) {
        loadData(); 
        return;
    }

    try {
        Connection conn = DBConnect.getConnection();
        
        // --- CÂU LỆNH SQL THÔNG MINH ---
        // Tìm kiếm: Hoặc Tên chứa từ khóa, Hoặc Mã NV chứa từ khóa
        String sql = "SELECT * FROM NhanVien WHERE HoTen LIKE ? OR MaNV LIKE ?";
        
        PreparedStatement ps = conn.prepareStatement(sql);
        
        // Dấu % ở hai đầu nghĩa là tìm "có chứa" (Ví dụ nhập "1" thì tìm ra 1, 10, 12, 21...)
        ps.setString(1, "%" + tuKhoa + "%"); // Tìm theo Tên
        ps.setString(2, "%" + tuKhoa + "%"); // Tìm theo Mã
        
        ResultSet rs = ps.executeQuery();
        
        // --- ĐOẠN NÀY COPY Y CHANG HÀM LOAD DATA ---
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã NV"); 
        model.addColumn("Họ Tên");
        model.addColumn("Chức Vụ");
        model.addColumn("Ngày Sinh");
        model.addColumn("Lương");
        model.addColumn("Tài Khoản");
        model.addColumn("Mật Khẩu");
        
        while (rs.next()) {
            Vector row = new Vector();
            row.add(rs.getInt("MaNV"));
            row.add(rs.getString("HoTen"));
            row.add(rs.getString("ChucVu"));
            row.add(rs.getDate("NgaySinh"));
            row.add((long)rs.getDouble("Luong")); 
            row.add(rs.getString("TaiKhoan"));
            row.add(rs.getString("MatKhau"));
            model.addRow(row);
        }
        // Cập nhật bảng với dữ liệu tìm được
        tblNhanVien.setModel(model);
        // -----------------------------------------------
        
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormNhanVien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
