/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Phan Huu Tuong
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement; // Thêm cái này phòng hờ
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class FormTraCuuHoaDon extends javax.swing.JFrame {
    // --- HÀM KHỞI TẠO ---
    public FormTraCuuHoaDon() {
        initComponents();
        this.setLocationRelativeTo(null); // Ra giữa màn hình
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Đóng form này không tắt app
        
        loadData(); // <--- GỌI HÀM TẢI DỮ LIỆU
        ((javax.swing.table.DefaultTableCellRenderer)tblHoaDon.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }

    // --- HÀM ĐỔ DỮ LIỆU TỪ MYSQL VÀO BẢNG ---
    private void loadData() {
        try {
            Connection conn = DBConnect.getConnection();
            
            // Câu lệnh này lấy dữ liệu từ 3 bảng: HoaDon, NhanVien, KhachHang
            // Để thay vì hiện số (1, 2) nó hiện Tên (Tường, Duy...)
            String sql = "SELECT H.MaHD, H.NgayLap, N.HoTen AS TenNV, K.HoTen AS TenKH, H.TongTien " +
                         "FROM HoaDon H " +
                         "JOIN NhanVien N ON H.MaNV = N.MaNV " +
                         "JOIN KhachHang K ON H.MaKH = K.MaKH";
            
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            // Tạo khung cho bảng
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Mã HĐ");
            model.addColumn("Ngày Lập");
            model.addColumn("Nhân Viên");
            model.addColumn("Khách Hàng");
            model.addColumn("Tổng Tiền");
            
            // Đổ dữ liệu vào
            while(rs.next()){
                Vector row = new Vector();
                row.add(rs.getInt("MaHD"));
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                row.add(sdf.format(rs.getTimestamp("NgayLap")));
                row.add(rs.getString("TenNV"));
                row.add(rs.getString("TenKH"));
                
                // Lấy tổng tiền (ép sang kiểu long cho mất số lẻ)
                row.add((long)rs.getDouble("TongTien"));
                
                model.addRow(row);
            }
            
            // Gán vào bảng giao diện
            tblHoaDon.setModel(model);
            
            // Chỉnh font cho đẹp (Optional)
            tblHoaDon.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            tblHoaDon.setRowHeight(25);
            
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tải hóa đơn: " + e.getMessage());
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTraCuuHoaDon.class.getName());
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnLamMoi = new javax.swing.JButton();
        btnHome1 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN");

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTimKiem.addActionListener(this::txtTimKiemActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tìm Hóa Đơn theo Ngày/KH/NV:");

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHoaDon);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);

        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnHome1.addActionListener(this::btnHome1ActionPerformed);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tra cứu Hóa Đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(273, 273, 273)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(btnTimKiem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLamMoi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoa))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jLabel5)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnTimKiem)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoa))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
       // 1. Xóa trắng ô tìm kiếm
    txtTimKiem.setText("");
    
    // 2. Gọi lại hàm loadData để tải lại danh sách mới nhất từ MySQL
    loadData();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String tuKhoa = txtTimKiem.getText().trim();

        if (tuKhoa.isEmpty()) {
            loadData();
            return;
        }

        try {
            Connection conn = DBConnect.getConnection();

            // --- SQL NÂNG CẤP: TÌM THÊM CẢ NGÀY LẬP ---
            // DATE_FORMAT(H.NgayLap, '%d/%m/%Y') chuyển ngày trong DB thành chuỗi '21/11/2025' để dễ tìm
            String sql = "SELECT H.MaHD, H.NgayLap, N.HoTen AS TenNV, K.HoTen AS TenKH, H.TongTien " +
            "FROM HoaDon H " +
            "JOIN NhanVien N ON H.MaNV = N.MaNV " +
            "JOIN KhachHang K ON H.MaKH = K.MaKH " +
            "WHERE N.HoTen LIKE ? OR K.HoTen LIKE ? OR DATE_FORMAT(H.NgayLap, '%d/%m/%Y') LIKE ?";

            java.sql.PreparedStatement ps = conn.prepareStatement(sql);

            // Set 3 tham số giống nhau (tìm bất kỳ đâu)
            ps.setString(1, "%" + tuKhoa + "%"); // Tìm Tên NV
            ps.setString(2, "%" + tuKhoa + "%"); // Tìm Tên KH
            ps.setString(3, "%" + tuKhoa + "%"); // Tìm Ngày (ví dụ nhập '21' tìm ra ngày 21)

            java.sql.ResultSet rs = ps.executeQuery();

            // --- Đổ dữ liệu ra bảng (Code cũ giữ nguyên) ---
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
            model.addColumn("Mã HĐ");
            model.addColumn("Ngày Lập");
            model.addColumn("Nhân Viên");
            model.addColumn("Khách Hàng");
            model.addColumn("Tổng Tiền");

            while (rs.next()) {
                java.util.Vector row = new java.util.Vector();
                row.add(rs.getInt("MaHD"));

                // Format ngày giờ đẹp
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
                row.add(sdf.format(rs.getTimestamp("NgayLap")));

                row.add(rs.getString("TenNV"));
                row.add(rs.getString("TenKH"));

                // Format tiền đẹp
                java.text.DecimalFormat df = new java.text.DecimalFormat("###,###");
                row.add(df.format(rs.getDouble("TongTien")));

                model.addRow(row);
            }
            tblHoaDon.setModel(model);

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // 1. Mở lại Form Chính
        new FormHoaDon().setVisible(true);

        // 2. Đóng Form Nhân Viên hiện tại đi
        this.dispose();
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // 1. Kiểm tra xem người dùng đã chọn dòng nào trên bảng chưa
    int row = tblHoaDon.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Vui lòng chọn hóa đơn cần xóa!");
        return;
    }

    // 2. Hỏi xác nhận cho chắc ăn (tránh xóa nhầm)
    int confirm = javax.swing.JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa hóa đơn này? (Không thể khôi phục)");
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            // Lấy Mã HĐ từ dòng đang chọn (Cột 0)
            String maHD = tblHoaDon.getValueAt(row, 0).toString();
            
            Connection conn = DBConnect.getConnection();
            
            // --- BƯỚC QUAN TRỌNG: XÓA CHI TIẾT TRƯỚC ---
            // Phải xóa hàng hóa trong đơn trước thì mới xóa được cái đơn
            String sqlChiTiet = "DELETE FROM ChiTietHD WHERE MaHD = ?";
            PreparedStatement ps1 = conn.prepareStatement(sqlChiTiet);
            ps1.setString(1, maHD);
            ps1.executeUpdate(); // Thực thi xóa chi tiết
            
            // --- BƯỚC TIẾP THEO: XÓA HÓA ĐƠN ---
            String sqlHoaDon = "DELETE FROM HoaDon WHERE MaHD = ?";
            PreparedStatement ps2 = conn.prepareStatement(sqlHoaDon);
            ps2.setString(1, maHD);
            ps2.executeUpdate(); // Thực thi xóa hóa đơn
            
            javax.swing.JOptionPane.showMessageDialog(null, "Xóa thành công!");
            
            // Tải lại bảng để mất dòng vừa xóa
            loadData();
            
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, "Lỗi xóa: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTraCuuHoaDon().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
