/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Phan Huu Tuong
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel; // Để xử lý ComboBox
import java.text.DecimalFormat; // Để định dạng tiền tệ

public class FormSanPham extends javax.swing.JFrame {
    // Model để quản lý dữ liệu của bảng
    DefaultTableModel modelSanPham;
    
    // Model để quản lý dữ liệu của ComboBox Loại SP
    DefaultComboBoxModel<String> modelComboBox;

    // Biến lưu mã sản phẩm đang chọn (để dùng cho Sửa/Xóa)
    int maSPDangChon = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSanPham.class.getName());

    /**
     * Creates new form FormSanPham
     */
    public FormSanPham() {
        initComponents();
       this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        // Cấu hình bảng (code cũ của bạn)
        tblSanPham.setRowHeight(25);
        tblSanPham.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

        // --- DÁN DÒNG NÀY ĐỂ CĂN GIỮA TIÊU ĐỀ ---
        ((javax.swing.table.DefaultTableCellRenderer) tblSanPham.getTableHeader().getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.JLabel.CENTER);
        // ----------------------------------------

        loadComboBoxLoaiSP();
        loadDataSanPham();
         // --- CÀI ĐẶT PLACEHOLDER BAN ĐẦU ---
        txtTimKiem.setText("Tìm theo tên SP...");
        txtTimKiem.setForeground(new java.awt.Color(153, 153, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        cboLoaiSP = new javax.swing.JComboBox<>();
        txtGiaBan = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnHome.addActionListener(this::btnHomeActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên SP");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Loại");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Giá bán");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Số lượng");

        txtTenSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cboLoaiSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiSP.addActionListener(this::cboLoaiSPActionPerformed);

        txtGiaBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGiaBan.addActionListener(this::txtGiaBanActionPerformed);

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimKiem.setText("Tìm theo tên...");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });
        txtTimKiem.addActionListener(this::txtTimKiemActionPerformed);

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Loại", "Giá bán", "Tồn kho", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cboLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSua)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLamMoi)))))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnLamMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // 2. Đóng Form Nhân Viên hiện tại đi
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void cboLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSPActionPerformed
     
    }//GEN-LAST:event_cboLoaiSPActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
       // 1. Lấy dòng được chọn
        int selectedRow = tblSanPham.getSelectedRow();
        
        if (selectedRow >= 0) {
            // 2. Lấy dữ liệu từ các cột của dòng đó
            // Cột 0 là Mã SP (ẩn hoặc hiện tùy bạn cấu hình, nhưng nó vẫn ở index 0 trong model)
            maSPDangChon = Integer.parseInt(modelSanPham.getValueAt(selectedRow, 0).toString());
            String tenSP = modelSanPham.getValueAt(selectedRow, 1).toString();
            String tenLoai = modelSanPham.getValueAt(selectedRow, 2).toString();
            // Giá bán cần xử lý bỏ dấu phẩy nếu có trước khi đưa lại vào textfield
            String giaBanStr = modelSanPham.getValueAt(selectedRow, 3).toString().replace(",", "");
            String soLuong = modelSanPham.getValueAt(selectedRow, 4).toString();
            // Mô tả có thể null, cần kiểm tra
            Object moTaObj = modelSanPham.getValueAt(selectedRow, 5);
            String moTa = (moTaObj != null) ? moTaObj.toString() : "";

            // 3. Đổ dữ liệu lên các ô nhập liệu
            txtTenSP.setText(tenSP);
            cboLoaiSP.setSelectedItem(tenLoai); // Tự động chọn loại tương ứng trong combobox
            txtGiaBan.setText(giaBanStr);
            txtSoLuong.setText(soLuong);
        
            
            // (Tùy chọn) Khóa nút Thêm, mở nút Sửa/Xóa khi đang chọn dòng
            btnThem.setEnabled(false);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
       // 1. Xóa trắng các ô nhập liệu
        txtTenSP.setText("");
        cboLoaiSP.setSelectedIndex(0); // Chọn lại dòng đầu tiên "Chọn loại SP"
        txtGiaBan.setText("");
        txtSoLuong.setText("");
        // Nếu bạn có txtMoTa thì thêm dòng: txtMoTa.setText("");
        
        // 2. Reset biến mã sản phẩm đang chọn
        maSPDangChon = -1;
        
        // 3. Mở khóa nút Thêm, khóa nút Sửa/Xóa
        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        
        // 4. Tải lại bảng để cập nhật dữ liệu mới nhất
        loadDataSanPham();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       // 1. Lấy dữ liệu từ giao diện
        String tenSP = txtTenSP.getText().trim();
        String tenLoai = cboLoaiSP.getSelectedItem().toString();
        String giaBanStr = txtGiaBan.getText().trim();
        String soLuongStr = txtSoLuong.getText().trim();
        // String moTa = txtMoTa.getText().trim(); // Nếu có TextArea mô tả

        // 2. Kiểm tra dữ liệu đầu vào (Validation)
        if (tenSP.isEmpty() || giaBanStr.isEmpty() || soLuongStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin (Tên, Giá, Số lượng)!");
            return;
        }
        if (cboLoaiSP.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Loại sản phẩm!");
            return;
        }

        try {
            // Chuyển đổi kiểu dữ liệu và kiểm tra số
            double giaBan = Double.parseDouble(giaBanStr);
            int soLuong = Integer.parseInt(soLuongStr);

            if (giaBan < 0 || soLuong < 0) {
                JOptionPane.showMessageDialog(this, "Giá bán và Số lượng phải là số dương!");
                return;
            }

            Connection conn = DBConnect.getConnection();

            // --- BƯỚC QUAN TRỌNG: LẤY MÃ LOẠI TỪ TÊN LOẠI ---
            // Vì trong bảng SanPham lưu MaLoai (số), nhưng trên combobox lại hiện TenLoai (chữ)
            String sqlGetMaLoai = "SELECT MaLoai FROM LoaiSP WHERE TenLoai = ?";
            PreparedStatement psMaLoai = conn.prepareStatement(sqlGetMaLoai);
            psMaLoai.setString(1, tenLoai);
            ResultSet rsMaLoai = psMaLoai.executeQuery();
            
            int maLoai = -1;
            if (rsMaLoai.next()) {
                maLoai = rsMaLoai.getInt("MaLoai");
            } else {
                 // Trường hợp này hiếm khi xảy ra nếu combobox load đúng
                 JOptionPane.showMessageDialog(this, "Lỗi: Không tìm thấy mã loại sản phẩm!");
                 conn.close();
                 return;
            }
            // ------------------------------------------------

            // 3. Thực hiện câu lệnh INSERT
            String sqlInsert = "INSERT INTO SanPham (TenSP, MaLoai, GiaBan, SoLuongTon) VALUES (?, ?, ?, ?)";
            // Nếu có mô tả: "INSERT INTO SanPham (TenSP, MaLoai, GiaBan, SoLuongTon, MoTa) VALUES (?, ?, ?, ?, ?)"
            
            PreparedStatement ps = conn.prepareStatement(sqlInsert);
            ps.setString(1, tenSP);
            ps.setInt(2, maLoai);
            ps.setDouble(3, giaBan);
            ps.setInt(4, soLuong);
            // Nếu có mô tả: ps.setString(5, moTa);

            int rows = ps.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
                // Reset lại giao diện và tải lại bảng
                btnLamMoiActionPerformed(evt); 
            }

            conn.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá bán và Số lượng phải là số hợp lệ!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi thêm sản phẩm: " + e.getMessage());
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
      // Kiểm tra xem đã chọn sản phẩm nào chưa
        if (maSPDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần sửa trong bảng!");
            return;
        }

        // 1. Lấy dữ liệu từ giao diện (Tương tự nút Thêm)
        String tenSP = txtTenSP.getText().trim();
        String tenLoai = cboLoaiSP.getSelectedItem().toString();
        String giaBanStr = txtGiaBan.getText().trim();
        String soLuongStr = txtSoLuong.getText().trim();
        // String moTa = txtMoTa.getText().trim();

        // 2. Validation (Tương tự nút Thêm)
        if (tenSP.isEmpty() || giaBanStr.isEmpty() || soLuongStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }
        if (cboLoaiSP.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Loại sản phẩm!");
            return;
        }

        try {
            double giaBan = Double.parseDouble(giaBanStr);
            int soLuong = Integer.parseInt(soLuongStr);
            if (giaBan < 0 || soLuong < 0) {
                 JOptionPane.showMessageDialog(this, "Giá và Số lượng phải dương!"); return;
            }

            Connection conn = DBConnect.getConnection();

            // Lấy Mã Loại từ Tên Loại
            String sqlGetMaLoai = "SELECT MaLoai FROM LoaiSP WHERE TenLoai = ?";
            PreparedStatement psMaLoai = conn.prepareStatement(sqlGetMaLoai);
            psMaLoai.setString(1, tenLoai);
            ResultSet rsMaLoai = psMaLoai.executeQuery();
            int maLoai = -1;
            if (rsMaLoai.next()) maLoai = rsMaLoai.getInt("MaLoai");

            // 3. Thực hiện câu lệnh UPDATE
            String sqlUpdate = "UPDATE SanPham SET TenSP=?, MaLoai=?, GiaBan=?, SoLuongTon=? WHERE MaSP=?";
            // Nếu có mô tả: "UPDATE SanPham SET TenSP=?, MaLoai=?, GiaBan=?, SoLuongTon=?, MoTa=? WHERE MaSP=?"

            PreparedStatement ps = conn.prepareStatement(sqlUpdate);
            ps.setString(1, tenSP);
            ps.setInt(2, maLoai);
            ps.setDouble(3, giaBan);
            ps.setInt(4, soLuong);
            // Nếu có mô tả: ps.setString(5, moTa); ps.setInt(6, maSPDangChon);
            ps.setInt(5, maSPDangChon); // Nếu không có mô tả thì tham số này là số 5

            int rows = ps.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật sản phẩm thành công!");
                btnLamMoiActionPerformed(evt); // Reset
            }

            conn.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi định dạng số!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi sửa sản phẩm: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
       
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String tuKhoa = txtTimKiem.getText().trim();
        if (tuKhoa.isEmpty()) {
            loadDataSanPham(); // Nếu ô tìm kiếm rỗng thì load lại tất cả
            return;
        }

        try {
            Connection conn = DBConnect.getConnection();
            // Câu lệnh tìm kiếm theo tên (sử dụng LIKE)
            String sql = "SELECT SP.MaSP, SP.TenSP, L.TenLoai, SP.GiaBan, SP.SoLuongTon, SP.MoTa " +
                         "FROM SanPham SP " +
                         "LEFT JOIN LoaiSP L ON SP.MaLoai = L.MaLoai " +
                         "WHERE SP.TenSP LIKE ? " + 
                         "ORDER BY SP.MaSP DESC";
            
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "%" + tuKhoa + "%"); // Thêm dấu % để tìm gần đúng
            ResultSet rs = ps.executeQuery();

            modelSanPham.setRowCount(0); // Xóa bảng cũ
            DecimalFormat df = new DecimalFormat("###,###");

            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getInt("MaSP"));
                row.add(rs.getString("TenSP"));
                row.add(rs.getString("TenLoai"));
                row.add(df.format(rs.getDouble("GiaBan")));
                row.add(rs.getInt("SoLuongTon"));
                row.add(rs.getString("MoTa"));
                modelSanPham.addRow(row);
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       if (maSPDangChon == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn xóa sản phẩm này không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection conn = DBConnect.getConnection();
                String sqlDelete = "DELETE FROM SanPham WHERE MaSP = ?";
                PreparedStatement ps = conn.prepareStatement(sqlDelete);
                ps.setInt(1, maSPDangChon);

                int rows = ps.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!");
                    btnLamMoiActionPerformed(evt); // Reset
                }
                conn.close();
            } catch (java.sql.SQLIntegrityConstraintViolationException e) {
                // Bắt lỗi khóa ngoại (nếu sản phẩm đã có trong ChiTietHD)
                JOptionPane.showMessageDialog(this, 
                        "Không thể xóa sản phẩm này vì đã tồn tại trong hóa đơn bán hàng!\n" +
                        "(Gợi ý: Bạn có thể cập nhật số lượng về 0 thay vì xóa)");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi xóa sản phẩm: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        // Nếu nội dung đang là placeholder, thì xóa trắng và đổi màu chữ về đen
        if(txtTimKiem.getText().equals("Tìm theo tên SP...")){
            txtTimKiem.setText("");
            txtTimKiem.setForeground(new java.awt.Color(0, 0, 0)); // Màu đen
        }
    }//GEN-LAST:event_txtTimKiemFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormSanPham().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
// --- HÀM LOAD DỮ LIỆU CHO COMBOBOX LOẠI SP ---
    private void loadComboBoxLoaiSP() {
        try {
            Connection conn = DBConnect.getConnection();
            String sql = "SELECT TenLoai FROM LoaiSP";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            // Khởi tạo model cho ComboBox
            modelComboBox = new DefaultComboBoxModel<>();
            
            // Thêm dòng đầu tiên là "Tất cả" hoặc "Chọn loại"
            modelComboBox.addElement("Chọn loại SP");

            // Duyệt result set và thêm tên loại vào model
            while (rs.next()) {
                modelComboBox.addElement(rs.getString("TenLoai"));
            }

            // Gán model vào ComboBox trên giao diện
            cboLoaiSP.setModel(modelComboBox);

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tải ComboBox: " + e.getMessage());
        }
    }
    // --- HÀM LOAD DỮ LIỆU CHO BẢNG SẢN PHẨM ---
    private void loadDataSanPham() {
        try {
            Connection conn = DBConnect.getConnection();
            
            // Câu lệnh JOIN 2 bảng để lấy Tên Loại thay vì Mã Loại
            String sql = "SELECT SP.MaSP, SP.TenSP, L.TenLoai, SP.GiaBan, SP.SoLuongTon, SP.MoTa " +
                         "FROM SanPham SP " +
                         "LEFT JOIN LoaiSP L ON SP.MaLoai = L.MaLoai " + 
                         "ORDER BY SP.MaSP ASC"; // Sắp xếp sản phẩm mới nhất lên đầu
            
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            // Lấy model của bảng hiện tại và xóa hết dữ liệu cũ
            modelSanPham = (DefaultTableModel) tblSanPham.getModel();
            modelSanPham.setRowCount(0);

            // Định dạng tiền tệ (ví dụ: 15000000 -> 15,000,000)
            DecimalFormat df = new DecimalFormat("###,###");

            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getInt("MaSP"));
                row.add(rs.getString("TenSP"));
                row.add(rs.getString("TenLoai")); // Hiển thị tên loại
                
                // Định dạng giá bán
                double giaBan = rs.getDouble("GiaBan");
                row.add(df.format(giaBan)); 
                
                row.add(rs.getInt("SoLuongTon"));
                row.add(rs.getString("MoTa"));

                modelSanPham.addRow(row);
            }

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu sản phẩm: " + e.getMessage());
        }
    }
}
