/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Phan Huu Tuong
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;

public class FormTaoHoaDon extends javax.swing.JFrame {
    DefaultTableModel modelGioHang;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTaoHoaDon.class.getName());

    /**
     * Creates new form FormTaoHoaDon
     */
    public FormTaoHoaDon() {
       initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
       // Cấu hình bảng Giỏ hàng
    modelGioHang = new DefaultTableModel();
    String[] cols = {"Mã SP", "Tên SP", "Đơn Giá", "Số Lượng", "Thành Tiền"};
    modelGioHang.setColumnIdentifiers(cols);
    tblGioHang.setModel(modelGioHang);
        
        // --- DÁN ĐOẠN NÀY VÀO ĐÂY ---
        
        // 1. Chỉnh font TIÊU ĐỀ (Header) - To, Đậm (Size 16)
        tblGioHang.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        
        // 2. Chỉnh font NỘI DUNG (Các dòng) - Vừa phải (Size 14)
        tblGioHang.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        
        // 3. Tăng chiều cao dòng cho thoáng (30 pixel)
        tblGioHang.setRowHeight(30);
        
       // 1. Tạo bộ render căn giữa
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        // 2. Áp dụng cho TẤT CẢ CÁC CỘT dữ liệu
        for (int i = 0; i < tblGioHang.getColumnCount(); i++) {
            tblGioHang.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        
        // 3. Áp dụng cho TIÊU ĐỀ (Header)
        ((javax.swing.table.DefaultTableCellRenderer)tblGioHang.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        // --------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        lblTongTien = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnXoaKhoiGio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnHome1.addActionListener(this::btnHome1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã Khách Hàng:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã Sản Phẩm:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Số lượng:");

        txtMaKH.addActionListener(this::txtMaKHActionPerformed);

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setText("THÊM VÀO GIỎ");
        btnThem.addActionListener(this::btnThemActionPerformed);

        tblGioHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGioHang);

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(255, 0, 51));
        lblTongTien.setText("TỔNG CỘNG: 0VNĐ");

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(0, 255, 102));
        btnThanhToan.setText("THANH TOÁN NGAY");
        btnThanhToan.addActionListener(this::btnThanhToanActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tạo Hóa Đơn & Thanh Toán");

        btnXoaKhoiGio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaKhoiGio.setText("XÓA KHỎI GIỎ");
        btnXoaKhoiGio.addActionListener(this::btnXoaKhoiGioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaKH)
                            .addComponent(txtMaSP)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaKhoiGio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThanhToan)
                    .addComponent(lblTongTien)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(409, 409, 409)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(465, 465, 465))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoaKhoiGio)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTongTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // 1. Mở lại Form Chính
        new FormHoaDon().setVisible(true);

        // 2. Đóng Form Nhân Viên hiện tại đi
        this.dispose();
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKHActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // 1. Lấy dữ liệu
    String maSP = txtMaSP.getText();
    String soLuongStr = txtSoLuong.getText();
    
    if(maSP.isEmpty() || soLuongStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập Mã SP và Số lượng!");
        return;
    }
    
    try {
        int soLuong = Integer.parseInt(soLuongStr);
        Connection conn = DBConnect.getConnection();
        
        // 2. Tìm sản phẩm trong kho
        PreparedStatement ps = conn.prepareStatement("SELECT * FROM SanPham WHERE MaSP = ?");
        ps.setString(1, maSP);
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            // 3. Kiểm tra tồn kho
            int tonKho = rs.getInt("SoLuongTon");
            if (soLuong > tonKho) {
                JOptionPane.showMessageDialog(null, "Kho chỉ còn " + tonKho + " sản phẩm!");
                return;
            }
            
            // 4. Tính tiền
            long giaBan = (long) rs.getDouble("GiaBan");
            long thanhTien = soLuong * giaBan;
            
            // 5. Thêm vào bảng
            modelGioHang.addRow(new Object[] {
                maSP, rs.getString("TenSP"), giaBan, soLuong, thanhTien
            });
            
            // 6. Cập nhật tổng tiền
            tinhTongTien();
            
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy Mã Sản Phẩm này!");
        }
        conn.close();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Số lượng phải là số nguyên!");
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // 1. Kiểm tra giỏ hàng
        if (modelGioHang.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Giỏ hàng trống! Vui lòng chọn sản phẩm.");
            return;
        }
        
        // 2. Kiểm tra Mã Khách Hàng
        String maKH = txtMaKH.getText().trim();
        if (maKH.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập Mã Khách Hàng!");
            txtMaKH.requestFocus();
            return;
        }

        Connection conn = null;

        try {
            conn = DBConnect.getConnection();
            conn.setAutoCommit(false); // --- BẮT ĐẦU TRANSACTION ---
            
            // --- BƯỚC A: TÍNH TỔNG TIỀN ---
            double tongTien = 0;
            for (int i = 0; i < modelGioHang.getRowCount(); i++) {
                tongTien += Double.parseDouble(modelGioHang.getValueAt(i, 4).toString());
            }

            // --- BƯỚC B: LƯU HÓA ĐƠN (Bảng HoaDon) ---
            // Lấy Mã NV từ biến toàn cục (Nếu null thì gán tạm là 1 để test)
            String maNV = (FormChinh.maNVDangNhap == null || FormChinh.maNVDangNhap.isEmpty()) ? "1" : FormChinh.maNVDangNhap;
            
            String sqlHD = "INSERT INTO HoaDon (NgayLap, MaNV, MaKH, TongTien) VALUES (NOW(), ?, ?, ?)";
            // Quan trọng: Phải có Statement.RETURN_GENERATED_KEYS để lấy lại số hóa đơn vừa sinh ra
            PreparedStatement psHD = conn.prepareStatement(sqlHD, Statement.RETURN_GENERATED_KEYS);
            psHD.setString(1, maNV);
            psHD.setString(2, maKH);
            psHD.setDouble(3, tongTien);
            psHD.executeUpdate();
            
            // Lấy ID (Mã HĐ) vừa tự động sinh ra
            ResultSet rsKey = psHD.getGeneratedKeys();
            int maHD = 0;
            if (rsKey.next()) {
                maHD = rsKey.getInt(1);
            }
               for (int i = 0; i < modelGioHang.getRowCount(); i++) {
    // Lệnh INSERT vào bảng ChiTietHD (Dùng cái MaHD số 5 ở trên)
    // Lệnh UPDATE trừ kho (Dùng cái MaHD số 5 ở trên)
}
            // --- BƯỚC C: LƯU CHI TIẾT & TRỪ KHO ---
            // Chuẩn bị câu lệnh
            String sqlChiTiet = "INSERT INTO ChiTietHD (MaHD, MaSP, SoLuong, DonGia, ThanhTien) VALUES (?, ?, ?, ?, ?)";
            String sqlKho = "UPDATE SanPham SET SoLuongTon = SoLuongTon - ? WHERE MaSP = ?";
            
            PreparedStatement psChiTiet = conn.prepareStatement(sqlChiTiet);
            PreparedStatement psKho = conn.prepareStatement(sqlKho);
            
            // Duyệt qua từng dòng trong giỏ hàng
            for (int i = 0; i < modelGioHang.getRowCount(); i++) {
                String maSP = modelGioHang.getValueAt(i, 0).toString();
                int soLuong = Integer.parseInt(modelGioHang.getValueAt(i, 3).toString());
                double donGia = Double.parseDouble(modelGioHang.getValueAt(i, 2).toString());
                double thanhTien = Double.parseDouble(modelGioHang.getValueAt(i, 4).toString());
                
                // 1. Lưu vào bảng ChiTietHD
                psChiTiet.setInt(1, maHD);
                psChiTiet.setString(2, maSP);
                psChiTiet.setInt(3, soLuong);
                psChiTiet.setDouble(4, donGia);
                psChiTiet.setDouble(5, thanhTien);
                psChiTiet.executeUpdate(); // Thực thi insert chi tiết
                
                // 2. Trừ tồn kho bảng SanPham
                psKho.setInt(1, soLuong);
                psKho.setString(2, maSP);
                psKho.executeUpdate(); // Thực thi trừ kho
            }
            
            // --- BƯỚC D: HOÀN TẤT ---
            conn.commit(); // CHỐT ĐƠN (Lưu tất cả thay đổi)
            JOptionPane.showMessageDialog(null, "Thanh toán thành công!");
            
            // Reset giao diện
            modelGioHang.setRowCount(0);
            lblTongTien.setText("0 VNĐ");
            txtMaKH.setText("");
            txtMaSP.setText("");
            txtSoLuong.setText("");
            
            // --- TỰ ĐỘNG CHUYỂN TRANG (Theo yêu cầu của bạn) ---
            this.dispose(); // Đóng form bán hàng
            new FormHoaDon().setVisible(true); // Mở lại form danh sách hóa đơn (để thấy dòng mới)
            
        } catch (Exception e) {
            e.printStackTrace();
            // --- ROLLBACK (HOÀN TÁC) NẾU CÓ LỖI ---
            try {
                if (conn != null) conn.rollback(); 
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Lỗi thanh toán: " + e.getMessage());
            
        } finally {
            // Đóng kết nối
            try {
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnXoaKhoiGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhoiGioActionPerformed
       // 1. Kiểm tra xem đã chọn dòng nào chưa
    int row = tblGioHang.getSelectedRow();
    
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm cần xóa trong giỏ hàng!");
        return;
    }
    
    // 2. Xóa dòng đó khỏi Model
    // (Lấy model trực tiếp từ bảng cho chắc ăn)
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblGioHang.getModel();
    model.removeRow(row);
    
    // 3. QUAN TRỌNG: Tính lại tổng tiền ngay lập tức
    tinhTongTien();
    }//GEN-LAST:event_btnXoaKhoiGioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTaoHoaDon().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoaKhoiGio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
private void tinhTongTien() {
    long tong = 0;
    try {
        // Duyệt qua bảng để cộng tiền
        for (int i = 0; i < modelGioHang.getRowCount(); i++) {
            tong += Long.parseLong(modelGioHang.getValueAt(i, 4).toString());
        }
        DecimalFormat df = new DecimalFormat("###,###");
        lblTongTien.setText("TỔNG CỘNG: " + df.format(tong) + " VNĐ");
    } catch (Exception e) { }
}
}
